import { useState } from 'react';
import {
  Card,
  CardTitle,
  CardBody,
  Button,
  Spinner,
  Alert,
  EmptyState,
  EmptyStateIcon,
  EmptyStateBody,
  EmptyStateHeader,
  Title,
  Grid,
  GridItem,
  Label,
  List,
  ListItem
} from '@patternfly/react-core';
import { CubesIcon, DownloadIcon, SyncAltIcon } from '@patternfly/react-icons';
import llmService from '../../services/llmService';
import { getActiveProvider, LLM_PROVIDERS } from '../../config/llmConfig';
import MicroservicesTierDiagram from './MicroservicesTierDiagram';
import BusinessLogicDocumentation from './BusinessLogicDocumentation';
import SpecKitExportButton from './SpecKitExportButton';
import JSZip from 'jszip';
import { generateAllSpecKitFiles } from '../../utils/specKitGenerator';
import { sanitizeFilename, downloadZip } from '../../utils/downloadUtils';

const MicroservicesDecomposition = ({ data }) => {
  const [decomposition, setDecomposition] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const activeProvider = getActiveProvider();

  const generateDecomposition = async () => {
    if (activeProvider === LLM_PROVIDERS.NONE) {
      setError('AI provider required for microservices decomposition. Please configure an API key.');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const result = await llmService.generateMicroservicesDecomposition(data);
      if (result) {
        setDecomposition(result);
      } else {
        setError('Failed to generate decomposition. Please try again.');
      }
    } catch (err) {
      console.error('Decomposition error:', err);
      setError(err.message || 'Failed to generate decomposition');
    } finally {
      setLoading(false);
    }
  };

  const exportAllSpecKits = async () => {
    if (!decomposition || !decomposition.microservices) {
      alert('No microservices to export');
      return;
    }

    // Warn for large exports
    if (decomposition.microservices.length > 10) {
      const confirmed = confirm(
        `You are about to export ${decomposition.microservices.length} services. This may take a moment. Continue?`
      );
      if (!confirmed) return;
    }

    try {
      const allServicesZip = new JSZip();

      // Create a folder for each service
      for (const service of decomposition.microservices) {
        const files = generateAllSpecKitFiles(
          service,
          decomposition.businessLogic || [],
          decomposition,
          data
        );

        const serviceFolderName = sanitizeFilename(service.name);
        const serviceFolder = allServicesZip.folder(serviceFolderName);

        // Add files to service folder
        serviceFolder.file('constitution.md', files.constitution);
        serviceFolder.file('spec.md', files.spec);
        serviceFolder.file('plan.md', files.plan);
        serviceFolder.file('tasks.md', files.tasks);

        // Add service-specific README
        const serviceReadme = `# ${service.name} - Spec-Kit

Type: ${service.type}

${service.description}

See parent README for usage instructions.
`;
        serviceFolder.file('README.md', serviceReadme);
      }

      // Add root README
      const rootReadme = `# ${data.applicationName} - Microservices Spec-Kits

This archive contains Spec-Kit specifications for all proposed microservices in the ${data.applicationName} modernization project.

## Services

${decomposition.microservices.map(s => `- **${s.name}** (${s.type}) - ${s.description}`).join('\n')}

## Structure

Each service folder contains:
- constitution.md - Development principles
- spec.md - Functional specification
- plan.md - Technical implementation plan
- tasks.md - Task breakdown
- README.md - Service-specific guide

## Usage

1. Extract this archive to your workspace
2. Review each service specification
3. Customize for your technology stack
4. Use with AI coding agents (Claude Code, Copilot, etc.)
5. Begin implementation following the task breakdown

## Spec-Kit Format

These specifications follow the [GitHub Spec-Kit](https://github.com/github/spec-kit) format for spec-driven development with AI.

---

Generated by Konveyor Visual Analysis Tool on ${new Date().toISOString().split('T')[0]}
`;

      allServicesZip.file('README.md', rootReadme);

      // Generate ZIP blob
      const blob = await allServicesZip.generateAsync({
        type: 'blob',
        compression: 'DEFLATE',
        compressionOptions: { level: 6 }
      });

      // Download
      const filename = `${sanitizeFilename(data.applicationName)}-all-spec-kits-${new Date().toISOString().split('T')[0]}.zip`;
      downloadZip(blob, filename);
    } catch (error) {
      console.error('Export all failed:', error);
      alert('Failed to export Spec-Kits. Please try again.');
    }
  };

  return (
    <Card>
      <CardTitle>
        <Title headingLevel="h2" size="xl">
          🎯 Microservices Decomposition Strategy
        </Title>
      </CardTitle>
      <CardBody>
        <div style={{ marginBottom: 'var(--pf-v5-global--spacer--md)', color: 'var(--pf-v5-global--Color--200)' }}>
          AI-powered analysis using Kubernetes best practices to suggest how to break down your monolith into microservices.
        </div>

        {!decomposition && !loading && (
          <EmptyState>
            <EmptyStateHeader titleText="Ready to Modernize Your Architecture?" icon={<EmptyStateIcon icon={CubesIcon} />} headingLevel="h3" />
            <EmptyStateBody>
              Generate a microservices decomposition strategy based on your application's current architecture,
              dependencies, and Kubernetes best practices.
            </EmptyStateBody>
            <Button
              variant="primary"
              onClick={generateDecomposition}
              isDisabled={activeProvider === LLM_PROVIDERS.NONE}
            >
              {activeProvider === LLM_PROVIDERS.NONE ? 'Configure AI Provider First' : 'Generate Microservices Strategy'}
            </Button>
          </EmptyState>
        )}

        {loading && (
          <EmptyState>
            <EmptyStateHeader titleText="Analyzing architecture..." icon={<EmptyStateIcon variant="container" component={Spinner} />} headingLevel="h3" />
            <EmptyStateBody>
              Generating microservices strategy... This may take 15-30 seconds
            </EmptyStateBody>
          </EmptyState>
        )}

        {error && (
          <Alert variant="danger" isInline title="Error">
            {error}
          </Alert>
        )}

        {decomposition && !loading && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--pf-v5-global--spacer--lg)' }}>
            {/* Strategy Overview */}
            {decomposition.overview && (
              <Alert variant="info" isInline title="📋 Strategy Overview">
                {decomposition.overview}
              </Alert>
            )}

            {/* Business Logic Documentation */}
            {decomposition.businessLogic && decomposition.businessLogic.length > 0 && (
              <BusinessLogicDocumentation businessLogic={decomposition.businessLogic} />
            )}

            {/* Tiered Architecture Diagram */}
            {decomposition.microservices && decomposition.microservices.length > 0 && (
              <MicroservicesTierDiagram microservices={decomposition.microservices} />
            )}

            {/* Proposed Microservices */}
            {decomposition.microservices && decomposition.microservices.length > 0 && (
              <div>
                <Title headingLevel="h3" size="lg" style={{ marginBottom: 'var(--pf-v5-global--spacer--md)' }}>
                  🔨 Proposed Microservices
                </Title>
                <Grid hasGutter>
                  {decomposition.microservices.map((service, idx) => (
                    <GridItem key={idx} md={6}>
                      <Card isCompact>
                        <CardTitle>
                          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', width: '100%' }}>
                            <div style={{ fontWeight: 'var(--pf-v5-global--FontWeight--semi-bold)' }}>
                              {service.name}
                            </div>
                            <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--pf-v5-global--spacer--sm)' }}>
                              <Label color="green" isCompact>
                                {service.type || 'Service'}
                              </Label>
                              <SpecKitExportButton
                                service={service}
                                businessLogic={decomposition.businessLogic}
                                decomposition={decomposition}
                                data={data}
                              />
                            </div>
                          </div>
                        </CardTitle>
                        <CardBody>
                          <div style={{ fontSize: 'var(--pf-v5-global--FontSize--sm)', color: 'var(--pf-v5-global--Color--200)', marginBottom: 'var(--pf-v5-global--spacer--md)' }}>
                            {service.description}
                          </div>

                          {service.components && service.components.length > 0 && (
                            <div style={{ marginBottom: 'var(--pf-v5-global--spacer--md)' }}>
                              <div style={{ fontSize: 'var(--pf-v5-global--FontSize--xs)', fontWeight: 'var(--pf-v5-global--FontWeight--semi-bold)', marginBottom: 'var(--pf-v5-global--spacer--sm)', color: 'var(--pf-v5-global--Color--200)' }}>
                                Components:
                              </div>
                              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--pf-v5-global--spacer--xs)' }}>
                                {service.components.map((comp, i) => (
                                  <Label key={i} isCompact>
                                    {comp}
                                  </Label>
                                ))}
                              </div>
                            </div>
                          )}

                          {service.responsibilities && service.responsibilities.length > 0 && (
                            <div style={{ marginBottom: 'var(--pf-v5-global--spacer--md)' }}>
                              <div style={{ fontSize: 'var(--pf-v5-global--FontSize--xs)', fontWeight: 'var(--pf-v5-global--FontWeight--semi-bold)', marginBottom: 'var(--pf-v5-global--spacer--sm)', color: 'var(--pf-v5-global--Color--200)' }}>
                                Responsibilities:
                              </div>
                              <List isPlain>
                                {service.responsibilities.slice(0, 3).map((resp, i) => (
                                  <ListItem key={i} style={{ fontSize: 'var(--pf-v5-global--FontSize--xs)' }}>
                                    • {resp}
                                  </ListItem>
                                ))}
                              </List>
                            </div>
                          )}

                          {service.patterns && service.patterns.length > 0 && (
                            <div style={{ marginBottom: 'var(--pf-v5-global--spacer--sm)' }}>
                              <div style={{ fontSize: 'var(--pf-v5-global--FontSize--xs)', fontWeight: 'var(--pf-v5-global--FontWeight--semi-bold)', marginBottom: 'var(--pf-v5-global--spacer--sm)', color: 'var(--pf-v5-global--Color--200)' }}>
                                Patterns Applied:
                              </div>
                              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--pf-v5-global--spacer--xs)' }}>
                                {service.patterns.map((pattern, i) => (
                                  <Label key={i} color="blue" isCompact>
                                    🏛️ {pattern}
                                  </Label>
                                ))}
                              </div>
                            </div>
                          )}

                          {service.communication && (
                            <div>
                              <div style={{ fontSize: 'var(--pf-v5-global--FontSize--xs)', fontWeight: 'var(--pf-v5-global--FontWeight--semi-bold)', marginBottom: 'var(--pf-v5-global--spacer--sm)', color: 'var(--pf-v5-global--Color--200)' }}>
                                Communication:
                              </div>
                              <div style={{ fontSize: 'var(--pf-v5-global--FontSize--xs)', color: 'var(--pf-v5-global--Color--200)' }}>
                                {service.communication}
                              </div>
                            </div>
                          )}
                        </CardBody>
                      </Card>
                    </GridItem>
                  ))}
                </Grid>
              </div>
            )}

            {/* Migration Strategy */}
            {decomposition.migrationStrategy && decomposition.migrationStrategy.length > 0 && (
              <div>
                <Title headingLevel="h3" size="lg" style={{ marginBottom: 'var(--pf-v5-global--spacer--md)' }}>
                  🚀 Migration Strategy
                </Title>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--pf-v5-global--spacer--md)' }}>
                  {decomposition.migrationStrategy.map((phase, idx) => (
                    <Card key={idx} isCompact style={{ borderLeft: '4px solid var(--pf-v5-global--palette--purple-500)' }}>
                      <CardBody>
                        <div style={{ display: 'flex', alignItems: 'flex-start', gap: 'var(--pf-v5-global--spacer--md)' }}>
                          <Label color="purple" isCompact>
                            Phase {phase.phase || idx + 1}
                          </Label>
                          <div style={{ flex: 1 }}>
                            <div style={{ fontWeight: 'var(--pf-v5-global--FontWeight--semi-bold)', marginBottom: 'var(--pf-v5-global--spacer--sm)' }}>
                              {phase.title}
                            </div>
                            <div style={{ fontSize: 'var(--pf-v5-global--FontSize--sm)', color: 'var(--pf-v5-global--Color--200)', marginBottom: 'var(--pf-v5-global--spacer--sm)' }}>
                              {phase.description}
                            </div>
                            {phase.patterns && phase.patterns.length > 0 && (
                              <div style={{ marginBottom: 'var(--pf-v5-global--spacer--sm)' }}>
                                <div style={{ fontSize: 'var(--pf-v5-global--FontSize--xs)', fontWeight: 'var(--pf-v5-global--FontWeight--semi-bold)', marginBottom: 'var(--pf-v5-global--spacer--xs)', color: 'var(--pf-v5-global--Color--200)' }}>
                                  Patterns:
                                </div>
                                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--pf-v5-global--spacer--xs)' }}>
                                  {phase.patterns.map((pattern, i) => (
                                    <Label key={i} color="blue" isCompact>
                                      📐 {pattern}
                                    </Label>
                                  ))}
                                </div>
                              </div>
                            )}
                            {phase.services && phase.services.length > 0 && (
                              <div>
                                <div style={{ fontSize: 'var(--pf-v5-global--FontSize--xs)', fontWeight: 'var(--pf-v5-global--FontWeight--semi-bold)', marginBottom: 'var(--pf-v5-global--spacer--xs)', color: 'var(--pf-v5-global--Color--200)' }}>
                                  Services:
                                </div>
                                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--pf-v5-global--spacer--xs)' }}>
                                  {phase.services.map((svc, i) => (
                                    <Label key={i} color="purple" isCompact>
                                      {svc}
                                    </Label>
                                  ))}
                                </div>
                              </div>
                            )}
                          </div>
                        </div>
                      </CardBody>
                    </Card>
                  ))}
                </div>
              </div>
            )}

            {/* Kubernetes Recommendations */}
            {decomposition.kubernetesRecommendations && decomposition.kubernetesRecommendations.length > 0 && (
              <div>
                <Title headingLevel="h3" size="lg" style={{ marginBottom: 'var(--pf-v5-global--spacer--md)' }}>
                  ☸️ Kubernetes Best Practices
                </Title>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--pf-v5-global--spacer--md)' }}>
                  {decomposition.kubernetesRecommendations.map((rec, idx) => (
                    <Card key={idx} isCompact>
                      <CardTitle>{rec.title}</CardTitle>
                      <CardBody>
                        <div style={{ fontSize: 'var(--pf-v5-global--FontSize--sm)', color: 'var(--pf-v5-global--Color--200)', marginBottom: 'var(--pf-v5-global--spacer--sm)' }}>
                          {rec.description}
                        </div>
                        {rec.implementation && (
                          <Card isFlat isCompact>
                            <CardBody>
                              <code style={{ fontSize: 'var(--pf-v5-global--FontSize--xs)' }}>
                                {rec.implementation}
                              </code>
                            </CardBody>
                          </Card>
                        )}
                      </CardBody>
                    </Card>
                  ))}
                </div>
              </div>
            )}

            {/* Data Considerations */}
            {decomposition.dataStrategy && (
              <Alert variant="warning" isInline title="💾 Data Management Strategy">
                {decomposition.dataStrategy.split('. ').map((sentence, idx) => {
                  if (!sentence.trim()) return null;
                  const text = sentence.trim() + (sentence.endsWith('.') ? '' : '.');
                  return <div key={idx} style={{ marginBottom: 'var(--pf-v5-global--spacer--sm)' }}>{text}</div>;
                })}
              </Alert>
            )}

            {/* Action Buttons */}
            <div style={{ display: 'flex', gap: 'var(--pf-v5-global--spacer--sm)', paddingTop: 'var(--pf-v5-global--spacer--md)', borderTop: '1px solid var(--pf-v5-global--BorderColor--100)' }}>
              <Button
                variant="secondary"
                onClick={generateDecomposition}
                icon={<SyncAltIcon />}
              >
                Regenerate Strategy
              </Button>
              <Button
                variant="primary"
                onClick={exportAllSpecKits}
                icon={<DownloadIcon />}
              >
                Download All Spec-Kits
              </Button>
            </div>
          </div>
        )}
      </CardBody>
    </Card>
  );
};

export default MicroservicesDecomposition;
