/**
 * Download Utilities
 * Handles ZIP file creation and browser downloads for Spec-Kit export
 */

import JSZip from 'jszip';

/**
 * Sanitize service name for use in filenames
 * Removes special characters and converts to lowercase
 */
export const sanitizeFilename = (name) => {
  return name
    .replace(/[^a-z0-9-_\s]/gi, '-')  // Replace special chars with dash
    .replace(/\s+/g, '-')               // Replace spaces with dash
    .replace(/--+/g, '-')               // Remove consecutive dashes
    .replace(/^-+|-+$/g, '')            // Remove leading/trailing dashes
    .toLowerCase();
};

/**
 * Generate safe filename for Spec-Kit ZIP
 */
export const generateSpecKitFilename = (serviceName) => {
  const sanitized = sanitizeFilename(serviceName);
  const timestamp = new Date().toISOString().split('T')[0];
  return `${sanitized}-spec-kit-${timestamp}.zip`;
};

/**
 * Create ZIP file containing Spec-Kit files
 * @param {string} serviceName - Name of the service
 * @param {Object} files - Object containing { constitution, spec, plan, tasks }
 * @returns {Promise<Blob>} ZIP file as blob
 */
export const createSpecKitZip = async (serviceName, files) => {
  try {
    const zip = new JSZip();

    // Add all Spec-Kit files to the ZIP
    zip.file('constitution.md', files.constitution);
    zip.file('spec.md', files.spec);
    zip.file('plan.md', files.plan);
    zip.file('tasks.md', files.tasks);

    // Optionally add a README
    const readme = `# ${serviceName} - Spec-Kit

This directory contains executable specifications for the ${serviceName} microservice.

## Files

- **constitution.md** - Development principles and architectural standards
- **spec.md** - Functional specification with business requirements
- **plan.md** - Technical implementation plan
- **tasks.md** - Detailed implementation task breakdown

## Usage

These files follow the [GitHub Spec-Kit](https://github.com/github/spec-kit) format and can be used with:
- Claude Code
- GitHub Copilot
- Cursor
- Windsurf
- Other AI coding agents

## Next Steps

1. Review each specification file
2. Customize for your specific technology stack
3. Use with your preferred AI coding agent to begin implementation
4. Update specifications as implementation progresses

Generated by Konveyor Visual Analysis Tool
`;

    zip.file('README.md', readme);

    // Generate ZIP blob
    const blob = await zip.generateAsync({
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 }
    });

    return blob;
  } catch (error) {
    console.error('ZIP generation failed:', error);
    throw new Error(`Failed to create ZIP file: ${error.message}`);
  }
};

/**
 * Create ZIP containing all microservices Spec-Kits
 * @param {string} applicationName - Name of the application
 * @param {Array} services - Array of service objects
 * @param {Array} businessLogic - Business logic array
 * @param {Object} decomposition - Full decomposition object
 * @param {Object} data - Application data
 * @param {Function} generateAllSpecKitFiles - Function to generate files for a service
 * @returns {Promise<Blob>} ZIP file as blob
 */
export const createAllServicesZip = async (
  applicationName,
  services,
  businessLogic,
  decomposition,
  data,
  generateAllSpecKitFiles
) => {
  try {
    const zip = new JSZip();

    // Create a folder for each service
    for (const service of services) {
      const files = generateAllSpecKitFiles(service, businessLogic, decomposition, data);
      const serviceFolderName = sanitizeFilename(service.name);
      const serviceFolder = zip.folder(serviceFolderName);

      // Add files to service folder
      serviceFolder.file('constitution.md', files.constitution);
      serviceFolder.file('spec.md', files.spec);
      serviceFolder.file('plan.md', files.plan);
      serviceFolder.file('tasks.md', files.tasks);

      // Add service-specific README
      const serviceReadme = `# ${service.name} - Spec-Kit

Type: ${service.type}

${service.description}

See parent README for usage instructions.
`;
      serviceFolder.file('README.md', serviceReadme);
    }

    // Add root README
    const rootReadme = `# ${applicationName} - Microservices Spec-Kits

This archive contains Spec-Kit specifications for all proposed microservices in the ${applicationName} modernization project.

## Services

${services.map(s => `- **${s.name}** (${s.type}) - ${s.description}`).join('\n')}

## Structure

Each service folder contains:
- constitution.md - Development principles
- spec.md - Functional specification
- plan.md - Technical implementation plan
- tasks.md - Task breakdown
- README.md - Service-specific guide

## Usage

1. Extract this archive to your workspace
2. Review each service specification
3. Customize for your technology stack
4. Use with AI coding agents (Claude Code, Copilot, etc.)
5. Begin implementation following the task breakdown

## Spec-Kit Format

These specifications follow the [GitHub Spec-Kit](https://github.com/github/spec-kit) format for spec-driven development with AI.

---

Generated by Konveyor Visual Analysis Tool on ${new Date().toISOString().split('T')[0]}
`;

    zip.file('README.md', rootReadme);

    // Generate ZIP blob
    const blob = await zip.generateAsync({
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 }
    });

    return blob;
  } catch (error) {
    console.error('All services ZIP generation failed:', error);
    throw new Error(`Failed to create all services ZIP: ${error.message}`);
  }
};

/**
 * Trigger browser download of a blob
 * @param {Blob} blob - File blob to download
 * @param {string} filename - Desired filename
 */
export const downloadZip = (blob, filename) => {
  try {
    // Create object URL for the blob
    const url = URL.createObjectURL(blob);

    // Create temporary link element
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.style.display = 'none';

    // Append to body, click, and cleanup
    document.body.appendChild(link);
    link.click();

    // Cleanup with slight delay to ensure download starts
    setTimeout(() => {
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, 100);
  } catch (error) {
    console.error('Download failed:', error);
    throw new Error('Failed to download file. Please check your browser permissions.');
  }
};
